import Link from "next/link";
import "./globals.css";
import { Open_Sans } from "next/font/google";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      <body>
        <header className="flex justify-between p-5">
          <h1 className="text-2xl font-bold">Hyeonwoo-Blog</h1>
          <ul className="flex gap-5">
            <Link href="/">home</Link>
            <Link href="/about">about</Link>
            <Link href="/posts">posts</Link>
            <Link href="/contact">contact</Link>
          </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
